version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    command:
      - --sql_mode=NO_ENGINE_SUBSTITUTION
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: passwd       # 更改為你的密碼
      MYSQL_DATABASE: test_db           # 預設資料庫
      MYSQL_USER: user                  # 使用者名稱
      MYSQL_PASSWORD: passwd            # 使用者密碼
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - mysql

  composer:
    image: composer:latest
    container_name: composer
    restart: unless-stopped
    volumes:
      - ./..:/app
    entrypoint: ["composer"]
    networks:
      - app-network

  php:
    image: php:8.3-fpm
    container_name: php
    restart: unless-stopped
    volumes:
      - ./..:/var/www/html
      - ./../composer:/usr/bin/composer # 掛載 Composer 到容器
    networks:
      - app-network
    depends_on:
      - composer

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./..:/var/www/html
      - ./../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
